(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.waterreflectioncoffee2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.6)").s().p("AFdMiQgBgMAXgNQB3hABwhRQAOgIAEAIIgDAQQhsBYiGBEIgPABQgJAAgCgDgApyKNQkTkhAKl4QABgiATgGQAPACAFAcQgZFnEkEtQAOAQgFAOQgEAEgHAAQgOAAgagTgAr2hWQgBgIAAgiQAAhOAQg8QAJgeAMgcQAYg3ATAAQAXAAgJAbQgFAOgMATIgQAjQgLAZgEATIgIBfQgIBRgHAAQgRAAgFgWgANZiiQhZlAjOjIQgNgMAJgNQAIgNAUAQQD5DjA3EuQAHAUgPAFIgHABQgMAAgGgNgAqKn4QgFgGAAgIQAAgQAugvQAkglAUgPQAcgUApgYQAqgZAdgNIAIgEIAKgDQALgDAHAAQARAAAAAFQAAAHg/ArIhKAyQg3ArgSAMIggAjQgdAfgJAAQgGAAgEgFgAmRpBQAAghBsgmQBXggAvgFIAAAAIAHgCQALgBAPACQAZADAAAIQAAAMgTAFQgaAFgPAEIhLAYQgQAFhGAbIhCAagAqqpIQgBgBAAgHQAAgQAzgtQAUgSAVgRIAEgDQAEgDAEAAIABAAQAFAAADAEQAEAEAAAGQAAANgzArQgxAqgHAAQgHAAgCgCgAnfrwQgDAAAAgFQAAgNAWgQQANgJANgHIAGgCIADAAQAMgBAAAPQAAAMgUANQgUANgTAAIgEAAIgDAAg");
	this.shape.setTransform(-22.4,-4.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.6)").s().p("ADxM9QgFgKAYgJQDshhCjigQALgRAOAGQAGAGgFANQidCvkJBfQgIAEgFAAQgHAAgCgGgApCKhQkfj1gcloQgBgpAXAJQANAEABATQAiFbEWDxQAbAYgOAMQgGAFgHAAQgNAAgUgPgANjgRQgMgDgBgWQgHkpiSjJQgRgRARgJQAPgFAPAPQCrDOgIEuQgFAfgVAAIgBAAgAq+pAQgFgEAAgEQAAgRAOgLQAZgWAEgFQAEACAIgBQADAAAAAHQAAAJgRAYQgRAYgLAAQgEAAgEgCgAm9spQAAgRAmgGIACAAIAEAAIAHgCQAEAAAAAGQAAAHgQAJQgOAJgJAAQgQAAAAgGg");
	this.shape_1.setTransform(-22.1,-2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0.6)").s().p("ACGKVIAGgCQFDhfDmkBQANgZALADQAKAEgNAVQjDEbl4BUgAoRITQkFiwhdlgQgKgtAagBQAKACAEAQQBUFNEPC8QAVAQgLATQgFAHgKAAQgKAAgQgHgAM+iHQAHlZhliqQAAgpAdAWIAAABQCFCtgMFHQgNA2gNAJQgHAFgGAAQgPAAgCgjg");
	this.shape_2.setTransform(-20.9,17.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(255,255,255,0.6)").s().p("AgqJ6QABgNASgBQIkhBD8n/QAJgVANAAQALABgDARQjxJMpMASIgCAAQgQAAgCgNgAjgJ+QnchliamcQgMgrAdgIQATgFANAnQBVDGCvB7QAbAjB3ALQB4ALAEA+QgCAhAbAHQAzALASASQAIAYgbAAQgKAAgOgDgAFIFzQgEgMANgMQA1geAugoQANgJAHAJQAKAHgPAPQguArg4AeQgIADgGAAQgFAAgCgEgAMpglQgOgJAPgbQAMhHgcAbQgcAdgSgVQgLgbAXgzQAUhCgDgsQgJjIgrhoQgPgdAbgOQATgGALATQCLEYhIEpQgIATgKAAQgDAAgEgCg");
	this.shape_3.setTransform(-17.6,20.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(255,255,255,0.6)").s().p("AksIxQkOhRhyiCQh1hxAqgOQANgFBZBfQDjCxHVhMQEPgqDPj0QCmi4BBivQAgi8gjh+QgKgoANgKQAggQAIAqQCxIOmiGjQkeDgkvAAQiAAAiCgngAjAIQQJ7BNERoxQAlhtgwAuQiFEYkRCKQjKBkk7gHQhPAIBpAcgAtCCyQgFgGAAgIQAAgIAFgFQAGgGAIAAQAIAAAFAGQAGAFAAAIQAAAIgGAGQgFAFgIAAQgIAAgGgFg");
	this.shape_4.setTransform(-16.4,24.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(255,255,255,0.6)").s().p("Aq5J4QgcgVgdgdQgigjAAgLQAAgEAFgNQAEgNAPADQAQACAeAbQAfAcAJgCQAKgDAFgNQAKgYAKgKQALgLAagGIAqgGQAPgTAUgIQATgIAqgEQBQgGA/gLQBPgMA3gPQBSgXA6gjIA3gjQAegUAHgLQALgRAVgTQAagWAUgFQAmgLA8gsQBJg2AbgOQEhjzhelkIgCgIIgCgJQgDgJAAgFQAAgOAJgMQALgNAUAAQAOAAARAPQAJAIAGAIQAjBIAGAwQAGAvgDANQgDAMADAOQADANAYAAQAIAAAIgEQAJgFAHAAQAXAAAWAcQALAOALAVQBSE1ihFSQjGGboOA5IgzABQlMAAkQjZgAiZLjQAAAtBkAAQAOAAANgCQIZhHCbnBQAShIgYgMQgPgJgaAtQi2FwlBBUIgZADIgbACQgTAAAAgKQAAgFAOgHQAOgHAAgMQAAgKgQgGQgLgFgKAAQgMAAhJANIhTAOQg3AAggADQg+AHAAAmQAAAXAkAOQAbALAYAAIAngFgAsOp4QAnh2DihiQAtgDgpAYQiYBNheB8QgUAXgGAAQgHAAAKgdg");
	this.shape_5.setTransform(-11.2,0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(255,255,255,0.6)").s().p("AmuMYIgZgQIgRgLQh/hLAeiSQAHg1AShnIAeikQAAg+g7iDQg7iBAAg8QAAhcAuhcQA/hrAjhCQAkhGBbg4QBmhABsAAQB0AABsBYIBLA9QAnAbAgAAIBYgNIBggFQAxgBAwAKQA6ALA3AZQA1AYAnArQApAsAgAwQC8EbjEHWQkaHTncAAQjLAAjvhVgAIZixQgGAIgjBIIgpBQIg5BtQgcA0goA3QgpA3hTA+QhUA+g6AgQhUAvhOARQhPARhLAwQhKAwAPBFQAPBFDHAmQB5AWB6gEQB5gFBSgzQBSgyBthZQBshZAzh7QAkhYAKhEQAHg2AAg2QgBg2gEg3QgEg4gSg1IgJgbQgbgzg4gYQgKgCgLAAQgxAAgaAjgAtgkbQgFgFAAgIQAAgNAEgJQAFgLAJAAQAMAAAAAPQAAAHgGANQgGAPgEAAQgEAAgFgEgAtFlwQgFgGAAgGIACgNQB6lDFHh+IAOgDQAJgCAFAAQAGAAAHACQAIADAAAEQAAAFgIAGIgQAKIAAAAQlNCOh3EyIgEAEQgDADgCAAQgGAAgEgGgAqeoVQgFgEAAgHQAAgFACgIQACgIADgBQAthHBSg3IAEgBIAEgCQAEgCADAAQAPAAAAAOIgBAGIgEAJQhKA0guBJIgDADIgIAGQgIAFgGAAQgFAAgEgEgAkxtIQgIgEAAgHQAAgNAcgHQAUgFAeAAIALABIACABIAHACQAHAEAAAFQAAAHgJADQgIADgTACQgpALgJAAQgFAAgGgDg");
	this.shape_6.setTransform(-19,-2.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(255,255,255,0.6)").s().p("An2LvIgQgQQgEgEgDgGQgEgIAAgGQAAgGAHgFQAFgEAFAAQAJAAAQAJIgBACQLJFQG5paQDMlGhJmBIgCgJIgDgJQgDgIAAgFQAAgFAEgHQAFgJAHAAQALAAALAQQAJAMAFAPQBeFYiEEuQiZFFlsCZQiZAuiRAAQj+AAjsiMgApgKhQgLgIAAgNQAAgHACgBQABgBAJAAIANACQANACADAHIAAADIADADIABADQAAAGgFAFQgEAFgGAAQgKAAgJgGgAklGSQhdgNhqg2QgsgWgjgkQgrgtgLgyIgXhaQgNg+AAgyIAAgqQABgYAFgOIgCgCQgEhXgJgWQgTgqguAAQgwAAgLAyQgHAbgDAHQgJAPgTAAQgXAAgNgUQgMgRAAgaQAAhQBBiEQBAiCBAg5QB9huB9hLQCVhZBZAAQBQAAAAA5QAAAVgpAXQgpAYAAASQAAAHAGADQAEACALAAQATAAArgIQAsgIASAAQArAABFA8QBGA7AkAAQAEAAAagJQAfgJAiAAQAWAAASADQBKAMAfBGQAdBBAEBGQAEASgFA+QgGA+AbBVQAJAkgEAeQgFArgaBHQgQArgWAqQgeA4gPAXQgcArgkAiQhNBHhdA0Qh4BEhdAAQiQAAgwgHg");
	this.shape_7.setTransform(-20.5,-3.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(255,255,255,0.6)").s().p("AhCOFQgYgJAAgQQAAgMAKgFQAIgDASAAIAeADIATgSQAUgTAOgGQAIgDAVAAQAXABAGgDQAJgDAzgXQAngRASgCIADAAQgCg8AMg7QARhXAshLQAshKA4hAQA5hABAg6QA9g5A8g6QA7g5BPgYIAoABQAGgXAJgrQAPhIAAgcQAAgXgIgmQgIgmAAgUIAAgVQACgOAKAAQAHAAAPAMQAPANAAAIQBZIHj6E1Qj5E0nnAaIgGABQgKAAgOgFgAkvNMIgggRQgZgOAAgHQAAgHAGgDQAFgBALAAIADAAQBHAYBKAPIAgAEQAYAHAAAPQAAANgEAFQgFAGgPAAQhMgHhFghgApHKqQgUgLAAgRQAAgNAPAAQANAAAOALIAYATIADAAIAAAQQgHAEgJAAQgRAAgQgJgAtZhUQgNgCgGgOQgLggAHggQAOg6ASg3QAQguATgtQAPgjASgiQBHiABwhcQBKg9BSgwQCqhjDBgjQARgFARABIADABIgBAAIABABIABgBQAoAAAPAFQAeAJAAAcQAAAYg4AYQgxAUgIAQIAAABIgBAEIAAAEIAEACQAJAWASAJQASAKAAAJQAAAXgOARQgCADgaAXQgSAPgGAVQAFAVABAWQAAAXgYAQQAJBFgGA7QgJA5gtAiQgWAPgUAQQgjAdgpAYQgsAcgwALQg1ALgygQIgigLIhggeQgWgFgQAQQgIAJgEAJQgGARgNAMQgNAGgFgMIgEgNQgCgWAJgUIAJgVQAIgOgDgOIgDgKQgagCgRAXQgfApgRAvQgIAXgLAWQgHANgMABIgSgLQgSAMABAYQAAAFgDAGQgFAKgMAAIgCAAg");
	this.shape_8.setTransform(-22.1,-4.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(255,255,255,0.6)").s().p("AACN/QgbgHAAgTQAAgNAcgHQAJgDA+gKQB0gUAigbQAigbAdgkQAeglABgjQAChBADgRQAIgqAagjQArg5BAhNQBBhMA7hAQBBhGBJgSQBIgSAZgfQAZgeAAgiQAAghgIg0QgIg0gFhIQgGhHABgSQACAAAEgHQAEgHANAOQAOAOAGAYQA3C9geB5QgNAtAGBQQg8E1klDkQjJCbkaAOIgEAAIgBAEIgogKgAigN6QgigKAAgSQAAgGAEgEQAEgGAHAAQAOAAAgAKQAwAHALADIABAAIAIADQAHADAAACQAAAOgPAGQgMAEgWAAQgbAAgagIgAoULCIgggVQg5gtAAgPQAAgMAMAAQALAAAVAPIAdAUIAyAhIACACIAHAGQAEADAAAFQAAAGgEAFQgFAGgHAAQgRAAgOgIgAt9AoIgGgdIAAgLQANlnDvkFQEdlAHiApQAKgBAVADQASAEAAALQAAAOgrAFIg0ADQgtAHg2AbQgRAIgYAgQgcAjgIAGQgDADgRAHIgJAHQgoAkAWA0IAAAAQAHAPACAaQACAagoArQgoArgrAmQgrAmgbAcIgtAtQg1AxgvACIgDAAIAAAAIgLgBQgVgCgcgJIgcgLQgJgEgOAAQgtAAgjArQgVAagdBAQgcA+gPARQgaAeghgSQAAAggVAMQgWANAAAFQAAAGAEASQADARAAAIIAAAVQgDAOgOAAIgBAAQgNAAgEgQgAKSoyQgZgVAAgNQAAgGADgDQADgCAHAAQALAAAJAGQAGAEALAKIANAMQAJAKAAAGQAAAEgFAEQgFAEgGAAQgMAAgTgPg");
	this.shape_9.setTransform(-22.4,-4.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(255,255,255,0.6)").s().p("AhBODQgrgJAAgLQAAgIAEgCQADgCAIAAQAWAAAsAFQA1AHAAAIQAAAEgFAIQgDAFgHACIgSAAQgWAAgkgHgABCNxQgNgRApgKIBHgPIA9gVQA2gRAMAAQAQAAAGAEQAGAEABALIABAEQgTAUhLAYQhLAYgdADIglACQgHAAgOgQgAF6MFQgQgOAAgRQAAgbAkhLIAmhKQASgvAkgvQAjgwAsgmQAOgMAbgUQAYgTAKgTQAMgVAZgXQAZgXAVgKQAIgEASgDQAMgBAHgJQAEgFANgMIAWgUQAHgGARgmQAOghAPAAQALAAAEALIAGASQhCHcmWCrIgEABIgEAAQgOAAgNgMgApNKcQgZgVgVgTQgqgnAAgMQAAgIAEgHQAEgHAHAAQAHAABbBAQARALAoAVQAfAUAAAZQAAALgEAPIAEAAIgFAFIgGABQgkAAhCg8gAtmDLQgJgdgCgCQhLmEEZluQFimXIWBqIADAAQAVAAAOAHQAOAJAAAOQAAAFgLADQgJACgHAAIhRgRQhNgRhDAFQhCAEgUADQgTACgDAUQgDATgUAGQgVAGgjAPIg/AbIANAPQAJAMgFAPQgFAPgZAVQgrANglAXIg/AlQgbAPhFBHQhGBHgnAAQgFAAgIgGIgGgEQguAzghBUQgNAggiBwQgDALgYANQgWAMgCAUIgCAmQgDAcAAANIgFAQQgCAJgDAFIgJAPQgEAIACAIQAFAUgLATQgMAUgTgFIAAArQACAVAOBcQACATgHAAQgNAAgLgdgANlAhQgKgRgCgSIgMhdIgJhIQAAgHAEgIQAEgKAEAAQATAAAGAeQADAPABAXQAFAPAJAXQAHAVAAAWIgBApQgBAVgHARQgEAIgEAAQgFAAgHgLgAJ1pPIgggZQgcgVAAgMQAAgIAEgEQAEgEAKAAQAWAAAUAVQAhAiAFAEQAPAKAOAcQATAjgiAAQgPAAglg6g");
	this.shape_10.setTransform(-22.6,-4.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(255,255,255,0.6)").s().p("AAvOFQgggFAAgOQAAgPAegCQAQgCAYACQBAAAgKATQgKAUgvAAQgUAAgPgDgADZNlQgWgBAAgQQAAgZAegLIAwgSQAggTBCgcQAhgOAKgPQAEgIAJgmQAFgUASgVQAKgLAWgUQCFhwA+iGQACgEgDgGQAFgLAKgOIAYgdQALgPASgJQAbgMAGgFQAGgEAZhDQAYhAAGAAQAOAAAHAWQAEAKAEAaQhTHooUDJIgJAEIgSABIgIgBgAm/MJQgOgDgFgDIgBgBQmFjNginZQgTl5DmklQEql2H3A4QCEASBjA/IAEAFIAIAHQALAKAAAKIAAAHQgBACgJAAIgjgGQh3hSi6gEQoigMkRJFQiXGpDDFcQACAHATAEQAWAFAFAEQARAMAcAhQAUAYBAA7QAaAYAaASQAPALAeASQAJAHAuAKQApANAAAXQAAAVgKAGQgIAEgcAAQgKAAgMgCgANJgQQgEgpAAgrQAAgJAEgDQAEgDAJAAQAGAAAJAFQAJAEACAGQABADAAAEIAHApQAFAbAAAPQAAA8geAAQgPAAgHhCgAKJmAQgPgPgSg1QgGgQgMgKIgVgPQgGgEgNgOIgagYQgQgPg7hcQgYglgFgfQgfggAAgIQAAgTAjAAIAMABIAFACIBtBCQA6ApAiAzQAZAlAuA2QAiAwAAA+QAAAng4AAQgjAAgPgQg");
	this.shape_11.setTransform(-21.3,-4.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(255,255,255,0.6)").s().p("ACWOCQgLgEAAgLQAAgHAXgHIAXgHIABAAIACgBQAOgFAhgDQAGAAAGAEQAEAEAAAFQAAASghAJQgYAHgTAAQgTAAgGgCgAEfM9QAAgUBNgrQBOgrACgSQACgRAegVQAogbADgEQAdgkAtgvQASgUArhIQAig4AogfQAVgRATgcIAdgtQAGgHAXgtQAPgcASAAQAHAAADAEQACAEAAANIAAAUQi2HglnB4IgJADQgigBAAgSgAnQMWQjPiBiDjeQi9lgC8mrIABgDQAFgMAKgMQAPgTADAAQAFAAAFACIAAAWQgUAdgMAiIgBADQhkEEBkFlQAlAEAbAhQAWAZALAmQAMAkAYAlQAZAmAdAXQArAiBiA6IBLAiQBFAiAAAZQAAAhgSANQgRALglAAQg2AAgSgHgANXBTIAAgqQgBggABgPQAEgdARAAQAEAAAFAHQAGAJADACQAEAXAAAtQAAAWgHATQgJAYgSAAQgHAAgCghgAiWBnQgTgIgDgEQgBgCAAgNQAAgEAEgMIADgMIAAgFIACgDIALAAIADAOQAEALACAEQADAFAJAHQAGAEAAAHQAAAFgCAGgAJ8kvQgTgMg1gxQgbgbgZguQggg8gFgIQgSgZgngiQg3gtgJgKQhHhHAShcQiniHmKBWIgDABIgGACIgeAKIghALIgkAPQgcAMgPAAQgPAAAAgMQAAgKAGgDQALgGAFgEIADAEQFPiPFGBbQF6CCCWFQIAPAhQABAEAAAYQAAAhgXANQgQAJgnAAQg1AAglgWgAoVrQQAFgNAMgMQALgMAOgDQADABAGgBIAJgBQAJAAAAAJQAAAJgUAOQgSAOgJAAQgGAAgQgFg");
	this.shape_12.setTransform(-22.2,-5.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(255,255,255,0.6)").s().p("ADcNsQgUgGAAgLQAAgLAKgGQAHgFARgBQANgCAOgIQAMgIAJAAQACAAAJAGQAIAGAEADIADAFQAAAPgXAPQgUAMgLAAQgSABgQgFgAFrM0QgWgCAAgNQAAgLAKgIIAPgNIADgCQFJjEB6kiIAGgKIAFgJQAIgPADgEIAVAAIAAAJQgDAJAAAWQhyFrlvCrIgQgBgAm4MVQmPizg4oQIAAgFQABgLAFgPQAHgVAJAAQAIAAAMAwIALA0IAQA3QAIAPAZAAQAnAAAhAwQARAaAcBBQAIAUAQAbQATAeANAMQANANAJAZQAFAPAJAeQAJAdAuAXQAMAHBSAgQA9AYAcAYQAnAgAAAuQAAAag6AYQgpAQgWABIgMgGgANlC3QgGgGAAgKQAAgGAGgXQAIgbAFAAQAFgBAFAKQAEAIAAAFQAAANgJAlIABADIgFABQgIAAgGgEgAjlCOQgWgeAAgrQAAgaAJgLQAJgLAbAAQAvAAABAuQACAgABAIQAFAUANANIADACIABABIABAFQAAAOgHAHQgHAGgQAAQgqAAgZghgAIIh/Qg+gagTgyQgUgygMgsQgNgrgMgdIgZg9QgNgjABgDQAAgBAAgBQAAgBAAAAQAAgBAAAAQgBAAAAAAIgHgOQgNgZgqgVQg2gcgMgLQgggcgPgjQgOggAAgsQAAgQAHgRQAHgSALgLQAGgHAVgIIAfgPQgagSg9gUQgggKhHgSIAAgHQAHgDAAgBIAzAAIACAAQEJApCKBsQEUDGANDNQAFgGABAFIABAKQAABYgvA5QgyA9hBAGIgWAAQg1AAgygVg");
	this.shape_13.setTransform(-22.4,-5.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(255,255,255,0.6)").s().p("AFBM7QgLgEAAgFQAAgMASgNQAQgLAKAAQANAAACABIAIAIIACACIgBACQgFAWgFAGQgHAGgXAAQgJAAgIgCgAsCHpQi6ksBvjuQAKhDA4AAQAsAAAaAaQAYAaAAArIgEA2QAAAKASAXQARAWAAARIgEApQAAApAaAiQARAVAtAjQAxAmAVAWQAlAoAPAxQAEAMAEAbQAFAXAMAIQAHAEAYAXQAVATARAHQA9AbAWAOQAHAEATAXQAXAdAAARQAAA7gWAdIgCACQgxA1hAAAQieAAj9k9gAGdL5QAAgNApgiQAZgUBDgzQCFhrAAhBQAAgUgMgDQgPgFgEgXQgDgMADgZQABgUgGgPQgIgUglgPQgwgUgHgFQgggZgMglQgEgPgGgvQgEgigMgOQgSgTgtAAQg9AAhGA3IgyAmQgbARgVAAQgeAAgWgJIgygZQgbgNgPgNQgKgJgRgFIgYgEQgUgEgXgRQgXgRgMgVQgSglgJgNQgPgWgXAAQgMAAgKAIQgMAJAAAOQAAAcAgA0IAfA0QAAAEgJAGQgLAIgNABQhIgLg4hpQhWigBkiGQg2knDmiyQDriyDkBLQG/DABGHVQA4Jhm+EeQgHAHgWALQgYAMgIAAQgRAAAAgTg");
	this.shape_14.setTransform(-22.2,-4.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(255,255,255,0.6)").s().p("AhEOAQqrhBiPrRQgXjkBIgoQAugbgDBPQgJB9BVgbQgHh2AmgNQgZkoFHhnQCEh8CtguQBLgkBRALIADgBIALgEQAOgGAAgKQAAgTg5AAQgRAAgnAHQgoAHgSAAQgIAAgkgIQglgIgRAAQggAAgvATQgvATgMAAQgQAAgOgIQgKgGgPgPIgtAZQgsAWgOAAIgJAAQgEgBAAgIQAAgeBIgnQA8giAvgLQHcicFlEQQHBFkhfIuQglCihUBtQgdAagUgTQglgOAlhJQCGl+iYkIQhDhUhDAcQg+AzAjBNQBkGci7AwQgnAPgWgRQgMggAMgfQA5hFgch6Qgsg0gtAsQgqE8mkg3QhVARA6BtQBGBTB+gMQBigsALCBQgJBzipAfQhCARAhAcQBAAjC8gjQBLAJgeBHQhSBViUAAQggAAgjgEgAiaggQgjAVANBEQAPB0CbAHQBLAHAmg2QANgrgzAAQicAjgYhzQgHgugWAAQgGAAgIAEg");
	this.shape_15.setTransform(-22.6,-4.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("rgba(255,255,255,0.6)").s().p("AsfG1QiUmFBQkrQAAgNAIgVQANgeASAAQALAAAAAVQAAAHgQB4QgRB3AAAiQAAAdAOALQAPALAEAxQAEAqAIAUQAMAdAYAAQASAAAEgQQACgHAAgVIgEgBQgDoMCig9QBlgwBWhOQCii2FgA2QASAHAsAJIAaAAQACgDAAgFQAAgKgYgPIgVgKIgIgEQighNk0AwQgeAIgKgEQgQgEAAgRQAAgOAEgEQAEgDAUgMIABAAQJIjSGlGnQFaG4idHBIgCAGIgJALQgLALgEAAQgCAAgVgMQgJAAgZAtQgZAsgRAAQgFAAgIgDQgKgFAAgHQAAgOAFgMIAOgVIADABQBZjhhYlAIAAgDQgagCgWgnQgGgLgYg3IgZg8QgRgigQgNQgggUgQgMQgfgWgSgdQgUgigWgPQgagRglAAQgGAAgFAEQgGAEAAAEQAAAKAKAHQAKAHADAEIADgEQDwEKh8B3QAAAAAAABQgBAAAAABQAAAAABABQAAABAAAAIAAADIAJAoQAIArAAATQAAAfgPA7QgOA0gNAfQgLAZghAoQgtA5ghAAQgJAAgDgEQgCgDAAgGQAAgJAJgLQAIgMAAgGQAAgGgNgDQgOgDAAgTQAAgLALgbQAKgbAAgWQAAgagJgUQgMgYgSAAQgLAAAAARIACAlQACA1guAAQggAAgMgiIgOhLQgJgxgXgYQgggihDAAQiKAAAABlQAAAvBAAIQBBAIAQAAQARAAgEAUQgEATgnAHQgcAFgVABIgBAAQAAADgRgBQgUAAgTgIQgNgFgJgGIgRgMQgWgSgCgaQAAghgDgTQgUgFgGgHQgFgHAAgNQAAgSAcgZQAbgYAAgSQAAgDgIgEQgHgEgCAAQgOAAgeAUQgcASgGAKQgWAgAAAxQAAAWAFATIANAuQADANAQASIAZAdQAYAgAxAMQAgAHA9AAQAXAAATgDQATgDAMAAQAMAAAIAKQAIAJAAAKQAAAchIASQg0AOgkAAQhTAAhIgvQhHgugYhCQhhjzDThxQD/h+DKDCQAPAsAcgeIAAgdQgxhthpguQkoh0jNDHQgpAcgiA/Qg6BxgaBYQgQETEaCPQBVAuBhgBQA7AMgFAsQghArhNgCQkyAGkEkdQgchcgcApQgJAvAmBIQClFnGsAyQCOAVCIgbIAkAHQAQAGAFARQAEARgUAPQgVAQgGgCQiJAih7AAQnGAAkWnDgAsxlhQgFgDAAgFQAAgPANgVQAKgPAKgJQAGgGAHgaQAGgTANAAQAZAAgNATQgXAZgGANQgFALgGAdQgIAYgRAAQgDAAgEgCgAm6rtQgKgCAAgKQAAgJAIgEQACgCAFAAIAKAAQAZAAAAAOQAAAIgFADQgFACgNAAIgKAAIgHAAg");
	this.shape_16.setTransform(-22,-5.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("rgba(255,255,255,0.6)").s().p("AqSJ+Qk/k7ByocIABgEIAFgHIAEgGQAJgMACgBIATAAIAAAWIgDAJIgBAGQhaH3EYEcQCUCCCpA1QAdAFA8AAQAuAAAaAPQAjAUAZAKQApAQAkAAQAJAAAogEIAxgFQAFAAAHAEQAHAEAAAFQAAALggAOQgWAKgOACIgEABQhHAOhHAAQkgAAj7j0gAHeLmIAAgKQAOgHAQgLIAVgOQABAAAAABQABAAABAAQAAAAABAAQABgBAAAAIADgBIAHgEQAIAAAAAKQAAAQgRALQgRALgVAAQgOAAgFgBgAofEzIgbgtQgKgPgWgpIgUgoQgJgSgpgtQgmgpgKgcQgJgagQg2QgVhKAAgWQAAh/Agg4QAdgyCBhuQB+hsBSguQCEhLCGAAQAdAAAQAMQATAOAAAdQAAAHgEAQIBDAJQA5AHAhALIBWAXQA8APAcAMQBFAdA+AwQBiBKAABHQAAA7gbAAQgTAAgNg4QgRhBgCgDQgSgYgXgWQgagXgXgMQhegxgxgNQg4gQheAAQgJAAgYADQgUACgLAAIgEAAQhEARgbAAQgOAAgfgJQgfgJghAAQg9AAhQAsQg2AdhVA/QgxAlgoA/QgmA/AAAoIACARIAOAAIBah3QA7hDAyAAQAEAAAEADQAEAEAAADQgYAWgeAkQg6BIgbBEQgaBEgJAqQgLAsAAAvQAAAYAFANIARAsQAEALADAeIAFAqQADATAIAVQAJAYANAOQAoAsAAAWQAAAKgHADQgEACgMAAQgVAAgagmgAM9DoQgjgXAJg8QAMl+jAjZQhdhigrhQQiOhzjQgdQhBgHgMghQhMgPh7AaQgcADgHghQg2AVgVgMQgfgZCFgVQIThVFsHEQDJEghMGcQgPAigVAAIgIgBgAtGkeQgGgFAAgJQAAgIAWgmIARgeQAJAEADAFQAFAHAAAMQgRBCgWAAQgHAAgEgEgAsLmFIgHgIQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAgBAAAAQAAgHAEgFIAAAAQAUAGAAAKQAAAFgCADgAr7myIgJgCIAAgUIATgLIAEADQAFADAEAAIAAAOIgFAJQgEAGgGAAIgIgCgArOn9QgGgEAAgDQAAgGAbgbQAagaAKgFIAIAEQAHADAAAEQAAAFgcAdQgcAdgJAAQgCAAgFgDgAmWsBQAAgMAWgKQAQgHAOgBIAJACIALABQgDAWg4APQgNAAAAgKg");
	this.shape_17.setTransform(-22.6,-5.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("rgba(255,255,255,0.6)").s().p("AltNbQpxkcBlrAQABgFADgFQAEgHAHgHQAOgOAMAAQANAAAAAVQAAALgDATIAAAEQhOKdIzD3IAKAEIAVAIQAVAJAAAOQAAAQgJAEQgHAEgYAAgAHGMdQgIgBAAgFQAAgIApgdIAvggIABgBIAFgCIAIgEQAGAAACAEQABADAAAJQAAATgpAZQgmAWgQAAIgFAAIgDAAgANGBxIgBgGQAFkqifjdQgJgNgRgSQgWgXgEgFQgDgFgdgZIgigdIg8g+QgegdgegQQg5ggghgRQgQgHgZgRIgngdQgegWgNgGQgKgFgIgMQgHgOgDgCQgGgDgngFQgkgEAAgFQAAgLAbgDQANgCAVgBIADgBIAAgCQFeA3D3FsQCCD5gKEMIgBAEQgDASgFAJQgKARgTAAQgSAAgKgigArlAnQgig9gCg+QgBg/AHgjQAHgjARggQgSgNAihFQAihFBAhFQBAhEAagYQAbgXAqgcQArgbBJgbQBIgcAdAAQAJAAAEAEQAEAEANAAQAgABAAASQAAANgNAJQgNAJgTAIIgxASIgcAJIg9AdIhEAjQgsAZgXAUQhXBPgXAaQg0A6gYBDIAbgTQAbgRAIAAQAPAAAAAKQAAAZgZA1QgZA2AAAfQAAAGARBhQAQBgAAAeQAAAUgBAJIgOACQgjAAg0hggAtbjNQgFgHAAgMQAAgdAYgOQAXgOAAAbIgEANQgFAMAAAHQAEAIgJAIQgIAIgGAAQgIAAgGgHgAsulYQAAgMAFgIIALgSQAGgBAGADQAIADAAAHQAAAMgEALQgGASgNAAQgNAAAAgPgAmsnEQgIgEAAgGQAAgjCThAQCLg9AwAAQAOAAAJADQAMAEAAAHIgBANQAugGAvAAQA3AAA0AJQBMAMAAAZQAAAHgEADQgCABgJAAQgHAAg6gIQg5gIgkAAQhGAAgZAMQgYAMgnAAQgxgDgPAAQgSABhFAUQgOAEg+AiQg4AfgMAAQgEAAgGgDgArXnpQAAgVA0g7QAugyAegSIAHgDQAGgDAEAAQAEAAAHAEQAAATgVASQgeAWgPAPIgkAyQgcAlgMAAQgOAAAAgLgAouqPQgGgCgBgIQAHgEAMgLQAGgFAIgDIAJACIACAAIAIAAQgFARgGAHQgHAHgOAAIgNAAgAnrq6QgEgBAAgGQAAgJAHgDIAMgFQACgCAEADQAEAEAAAFQAAAEgFAFQgGAFgIAAIgEABIgCgBgAm/rhQAAgTBeghQAsgPAtgNIAEgBIAEABIAPACIAAAEQgLANgYAHQggAJgTAGQgKAEgvAZQgoAWgLAAQgMAAAAgMgAjasvIgHgCQAGgVAJAAQAJAAADACQAEACAAAFQAAAJgEADQgDADgKAAIgHgBgAi0s+QAAgGADgEQAEgFAFgBIADAEQAFABAEADQADADAAACQAAAMgMAAQgPAAAAgJgAiFtOQAAgIAPgEQALgDAPgBIABABIABAAIAKAFQAGADAEgBIAAAHQgJAKgIACIgSAAQgcAAAAgLg");
	this.shape_18.setTransform(-21.9,-8.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("rgba(255,255,255,0.6)").s().p("Am9M9IgVgGIgCgBQnQjrAkpkIABgMQACgSAEgKQAIgWARAAQAMAAAAAKIgDASQgCAKAAAHIgBAEQgiI4GwEEIABABIABAAIAjAKQAcAHAAAKQAAAKgIACQgEACgNAAQgLAAgOgDgAGSM9QgGgBAAgHQAAgKANgHQAEgDAVgHQASgHAlgWQALgHBLg7QAMAAAAAHQAAAghGAuQhDAtglAAIgGAAIgFAAgAq9CBQgtglAEhmQADhnAIgmQAHgnAGgpQgFADgEAAQgOAAgFgKQgEgHAAgYQAAgYAFgNQAGgNAlg3QAlg4AegfQAeggAvgpQAugoBUgtQBegyBWgOIAAgCIAZAAIAdAIQgBAJgRAFIgRAEIgGACIgDAAQhXAYhRAsQhGAnhLA8QglAeg4BSQg4BSgCARIgDAZQgBAIARgGQADgPAFgGQAVgYANAAQAHAAAEADQAEADAAAEIgSAeQgSAfgEAKQgGAQgGAbIgKApQgDANgGBAQgGA+AAAXQgBAWAIAiQAIAiADACIAAAHgANfB5QgDgGAAgIQAAgPABgDQAGiJg3ifQgZgmgPglQh3kVj1iNIgIgEIgIgGIgIgJQgHgHAAgCQAAgSAWAAQARAAAIAEIAAABQG6D6AhI0IAAAFQABAJgBAEQgBAGgEAIIgJAOQgIAJgGAAQgFAAgDgHgAtii+QgDgEAAgGQAAgKAGgSQAIgaAMAAQAHAAAEAJQAEAHgCAEQgVAygIAAQgEAAgDgGgAnGmxQAAgHAGgJQAGgJAIgGQDSiaEQAZIADgBIAZAIQAZAJAAAHQAAANgWAAQgQAAgIgEQj6gUjaCPIgHAFIgJAGQgEAEgJAAQgMAAAAgKgArTneQgCgCAAgFQAAgMATgVQALgNANgLIAIgGIABgBIAFAAQAEAAAIADQAJADAAAEQgzA+gRAAQgGAAgCgBgAp9o8IAAgMQABgDAKgIQAKgIAEAAQAHAAAAANQAAAIgHAGQgGAGgKAAIgJgCgAn9q1QAAgFALgJQALgKAHAAQABAAABAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAABABAAQAAAAABAAIAAAJIgLAMQgGAFgIAAQgKAAAAgGgAmxreQAAgWBlgeQAygPAzgLQANAAAAAIQAAAJgMAAQg4AOhLAcIhAAZQgIgBAAgFgAiPswQgGgBAAgEQAAgLAQACQAQABACAHQgEAFgEAAIgLABIgFAAIgEAAg");
	this.shape_19.setTransform(-21.5,-10.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},2).to({state:[{t:this.shape_2}]},2).to({state:[{t:this.shape_3}]},2).to({state:[{t:this.shape_4}]},2).to({state:[{t:this.shape_5}]},2).to({state:[{t:this.shape_6}]},2).to({state:[{t:this.shape_7}]},2).to({state:[{t:this.shape_8}]},2).to({state:[{t:this.shape_9}]},2).to({state:[{t:this.shape_10}]},2).to({state:[]},1).to({state:[{t:this.shape_11}]},141).to({state:[{t:this.shape_12}]},2).to({state:[{t:this.shape_13}]},2).to({state:[{t:this.shape_14}]},2).to({state:[{t:this.shape_15}]},2).to({state:[{t:this.shape_16}]},2).to({state:[{t:this.shape_17}]},2).to({state:[{t:this.shape_18}]},2).to({state:[{t:this.shape_19}]},2).to({state:[]},2).wait(108));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-111.6,-84.6,178.5,161.1);


// stage content:
(lib.table_top_book_Canvas = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{step0:6,step1:8,step2:10,step3:12,step4:14,step5:16,step6:18,step7:20,step8:22,step9:24,step10:26});

	// timeline functions:
	this.frame_6 = function() {
		this.stop();
	}
	this.frame_8 = function() {
		this.stop();
	}
	this.frame_10 = function() {
		this.stop();
	}
	this.frame_12 = function() {
		this.stop();
	}
	this.frame_14 = function() {
		this.stop();
	}
	this.frame_16 = function() {
		this.stop();
	}
	this.frame_18 = function() {
		this.stop();
	}
	this.frame_20 = function() {
		this.stop();
	}
	this.frame_22 = function() {
		this.stop();
	}
	this.frame_24 = function() {
		this.stop();
	}
	this.frame_26 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(6).call(this.frame_6).wait(2).call(this.frame_8).wait(2).call(this.frame_10).wait(2).call(this.frame_12).wait(2).call(this.frame_14).wait(2).call(this.frame_16).wait(2).call(this.frame_18).wait(2).call(this.frame_20).wait(2).call(this.frame_22).wait(2).call(this.frame_24).wait(2).call(this.frame_26).wait(10));

	// Layer 1
	this.instance = new lib.waterreflectioncoffee2();
	this.instance.parent = this;
	this.instance.setTransform(731.5,233.1,0.797,0.797,0,0,0,-22.2,-3.9);
	this.instance.alpha = 0.148;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(36));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1195.2,493.7,142.3,128.4);
// library properties:
lib.properties = {
	id: '29AD54EE525A1547AD9D47C5C977BB98',
	width: 1070,
	height: 650,
	fps: 31,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['29AD54EE525A1547AD9D47C5C977BB98'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;